### ISSUE TITLE
Use a simple image as background

### ISSUE THREAD

**Issue by Simof92** [littlevgl/stm32f746_disco_no_os_atollic#1] opened 2019-01-30 19:24 UTC
Hi,

I am learning lvgl and I am trying to use an image as a background.
I took a part of the demo code but the screen remains completely black, the same code compiled on the PC with codeblocks works correctly.

Are there difference between the two platforms? 

void demo_create(void)
{
    lv_obj_t * wp = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(wp, &img_bubble_pattern);
    lv_obj_set_width(wp, LV_HOR_RES * 4);
    lv_obj_set_protect(wp, LV_PROTECT_POS);
}

![backscreen](https://user-images.githubusercontent.com/46396900/52006629-ea0a9080-24cc-11e9-94ce-d66f9cc095b3.PNG)

**Comment by kisvegabor** [comment] 2019-01-30 20:40
HI,

Is it working with the original demo?

**Comment by Simof92** [comment] 2019-01-30 20:54
Yes it work perfectly with the original demo code.

Il giorno mer 30 gen 2019, 21:40 Gabor Kiss-Vamosi <notifications@github.com>
ha scritto:

**Comment by kisvegabor** [comment] 2019-01-30 21:02
Let's try this code. Some lines from your example were specific to the original demo. If not working try to enable it line-by-line.
```c
    LV_IMG_DECLARE(img_bubble_pattern);
    lv_obj_t * wp = lv_img_create(lv_scr_act(), NULL);
    lv_img_set_src(wp, &img_bubble_pattern);
    lv_obj_set_pos(wp, 0, 0);
    lv_obj_set_width(wp, LV_HOR_RES);
```


Also, clean the project and be sure if it compiles without errors and warnings.

**Comment by Simof92** [comment] 2019-01-31 12:35
I tried like you suggested, the result is always a black screen.

**Comment by kisvegabor** [comment] 2019-01-31 15:10
As a reference can you try the SW4STM32 project? https://github.com/littlevgl/stm32f746_disco_no_os_sw4stm32

**Comment by Simof92** [comment] 2019-01-31 19:35
With SW4STM32 project it work fine... I must have entered a bug

**Comment by kisvegabor** [comment] 2019-02-01 06:57
Have you tried to clone the repo again? I don't have that board so couldn't try myself.

I saw that lvgl and lv_examples are added as normal files. Using submodules would be better to make libraries' update easier. In addition v5.3 is released.  Please try with that too.

**Comment by Simof92** [comment] 2019-02-01 07:02
I'm not expert of github, can you update the repo as you suggested?
With submodules of examples and lvgl 5.3?


Il giorno ven 1 feb 2019, 07:57 Gabor Kiss-Vamosi <notifications@github.com>
ha scritto:

**Comment by embeddedt** [comment] 2019-02-01 12:23
@Simof92 Done in https://github.com/littlevgl/stm32f746_disco_no_os_atollic/commit/f041fb59d5129ab5722e027e1a4f32217d4f0f4f.

**Comment by Simof92** [comment] 2019-02-01 17:31
@embeddedt  thank you


`  demo_create();

  lv_obj_t * wp = lv_img_create(lv_scr_act(), NULL);
  lv_img_set_src(wp, &img_bubble_pattern);
  lv_obj_set_pos(wp, 0, 0);
  lv_obj_set_width(wp, LV_HOR_RES);
`

If I call demo_create() before the creation of background it work, without demo_create function i have only black screen.

Am I forgetting something?

**Comment by kisvegabor** [comment] 2019-02-02 02:35
Getting even stranger.

Do you have any warnings?

Can you use the tft driver, and lv_conf.h from the SW4STM32 project?

If you debug the code step-by-step what happens in  `lv_img_set_src`?

**Comment by Simof92** [comment] 2019-02-02 17:29
Yes the tft driver is the same of SW4STM32 project such as lv_conf.h

This project compared to the STM32 project has only one other structure and the STM32CubeMx file

**Comment by Simof92** [comment] 2019-02-02 17:30
I have compared the lv_trace_log and the flow is the same

**Comment by Simof92** [comment] 2019-02-02 17:41
SOLVED: The problem was the optimization of compiler!! 
![resolved](https://user-images.githubusercontent.com/46396900/52167350-1404c280-271a-11e9-8043-ffdfb79b1341.PNG)

**Comment by kisvegabor** [comment] 2019-02-02 18:38
It wasn't working with O3?

**Comment by Simof92** [comment] 2019-02-02 18:43
Work with "Optimize most -O3"
 Doesn't work with "Optimize Size"

**Comment by kisvegabor** [comment] 2019-02-02 18:53
Very interesting. Is it the same with the SW4STM32 version?

**Comment by Simof92** [comment] 2019-02-02 18:58
Yes I found the problem by comparing this project with SW4STM32 project.

Il giorno sab 2 feb 2019, 19:53 Gabor Kiss-Vamosi <notifications@github.com>
ha scritto:

**Comment by embeddedt** [comment] 2019-02-02 21:39
@kisvegabor @Simof92 The SW4STM32 project doesn't work at all if you change optimization to `-Os`. See https://github.com/littlevgl/stm32f746_disco_no_os_sw4stm32/issues/1.

**Comment by kisvegabor** [comment] 2019-02-03 01:10
I see, thank you for the test.
Would you like to investigate what happens?

@Simof92 Please update the project with -O3 configuration.

**Comment by kisvegabor** [comment] 2019-02-03 01:30
I've tested the STM32F429-DISCO project. It's also not working with -Os. If the GPU is enabled teh background is not copied at all. Without GPU 16 bit colors are swapped.

My guess was that the `lv_flush_ready` is optimized out and the library didn't wait until the DMA "releases" the VDB. But it was working fine.

Now I think that the bug is in the STM drivers directly.

**Comment by embeddedt** [comment] 2019-02-03 01:43
@kisvegabor If you're having the same problem on F4 then I'm 99% sure the problem is with the drivers.

I will take a look and see if I can find anything, but it might be a few days before I start.

I wish I had tried this before the release!

**Comment by kisvegabor** [comment] 2019-02-03 01:51
I've found something. In `tft_flush` the address of `color_p` is `0x20000fa5`. But it should be aligned to 4 for proper DMA operation.

I've changed [this](https://github.com/littlevgl/lvgl/blob/4cd13016d34aff903090d4e1efce25866a1a676a/lv_core/lv_vdb.c#L39) line to  
`static uint8_t __attribute__((aligned(4))) vdb_buf[LV_VDB_SIZE_IN_BYTES];` and now it's working for me.

I suggest introducing a define in `lv_conf.h`: `LV_ATTRIBUTE_VDB_BUF` and push it to master as a bugfix.

**Comment by embeddedt** [comment] 2019-02-03 01:54
@kisvegabor Makes sense. I'd expect the DMA to require 4-byte alignment.

I'll test it in a few minutes and let you know if it works. Does this fix need to be applied to any other buffers?

**Comment by kisvegabor** [comment] 2019-02-03 01:55
> Does this fix need to be applied to any other buffers?

I don't think so because only the VDB buffer "touches" the hardware.

**Comment by embeddedt** [comment] 2019-02-03 02:02
@kisvegabor It hasn't completely resolved the problem on my end (Using `-Os`). Now the colors are correct, and the background is copied (somewhat), but there is still a lot of vertical duplication.

I tried with `aligned(4)` and `aligned(8)`.

**Comment by kisvegabor** [comment] 2019-02-03 02:54
@embeddedt 
Are you using GPU or LV_VDB_DOUBLE? 

With LV_VDB_DOUBLE the alignment should be added to the other VDB buffer too.

**Comment by embeddedt** [comment] 2019-02-03 03:13
@kisvegabor I think I'm using GPU, but not LV_VDB_DOUBLE. I'll confirm as soon as possible.

**Comment by Simof92** [comment] 2019-02-04 08:39
> 
> 
> I've found something. In `tft_flush` the address of `color_p` is `0x20000fa5`. But it should be aligned to 4 for proper DMA operation.
> 
> I've changed [this](https://github.com/littlevgl/lvgl/blob/4cd13016d34aff903090d4e1efce25866a1a676a/lv_core/lv_vdb.c#L39) line to
> `static uint8_t __attribute__((aligned(4))) vdb_buf[LV_VDB_SIZE_IN_BYTES];` and now it's working for me.
> 
> I suggest introducing a define in `lv_conf.h`: `LV_ATTRIBUTE_VDB_BUF` and push it to master as a bugfix.

With GPU enabled and single VDB I made the change you suggested, the result is the vertical moltiplication of the image with `-Os`

**Comment by kisvegabor** [comment] 2019-02-04 08:42
Send a photo, please.

**Comment by Simof92** [comment] 2019-02-04 09:10
I'm tryng different combinations of optimization and the options `prepare dead code removal` and `prepare dead data removal`

**Comment by Simof92** [comment] 2019-02-04 10:15
![result](https://user-images.githubusercontent.com/46396900/52201756-ba60dd00-286c-11e9-8d2c-5772c125f29b.PNG)

![img1](https://user-images.githubusercontent.com/46396900/52202014-8fc35400-286d-11e9-9110-2441b67a116f.jpg)
![img2](https://user-images.githubusercontent.com/46396900/52202020-92be4480-286d-11e9-8384-4ec5f914f911.jpg)
![img3](https://user-images.githubusercontent.com/46396900/52202021-9356db00-286d-11e9-9c17-e0d97ca014ed.jpg)
![img4](https://user-images.githubusercontent.com/46396900/52202024-93ef7180-286d-11e9-87ae-3ea2103dae7f.jpg)
![img5](https://user-images.githubusercontent.com/46396900/52202032-96ea6200-286d-11e9-9793-bb91f3e1cfc3.jpg)

**Comment by Simof92** [comment] 2019-02-04 10:18
The only configuration for which the operation is always correct is the number 8:
`Prepare dead copper removal` deselected
`Prepare dead data removal` deselected 
`static uint8_t __attribute__((aligned(4))) vdb_buf[LV_VDB_SIZE_IN_BYTES];`

**Comment by kisvegabor** [comment] 2019-02-04 10:27
Oh, I see. Let's add the alignment to the big array `img_bubble_pattern.c`. It should solve to vertical repeating issues.

**Comment by Simof92** [comment] 2019-02-04 11:08
I've retried the seventh configuration and with the alignment of img_bubble_pattern_map[] it work fine

**Comment by kisvegabor** [comment] 2019-02-04 11:47
Great! Adding the alignment here too should solve the rest of the problems: https://github.com/littlevgl/lvgl/blob/master/lv_draw/lv_draw_vbasic.c#L150

**Comment by embeddedt** [comment] 2019-02-04 12:00
@Simof92 @kisvegabor The behavior I saw on my board was very similar to images 2, 4, and 5.

What I'm wondering is why isn't the compiler aligning the variables to a 4-byte boundary automatically? I checked the linker script; there's nothing unusual there.

**Comment by kisvegabor** [comment] 2019-02-04 12:09
I think when the compiler optimizes for size it doesn't want to leave gaps. In the worst case,  a 3 byte gap can remain if the variables are aligned to 4 byte boundary.

**Comment by Simof92** [comment] 2019-02-04 12:37
I've tested the fifth and sixth configurations with demo and with background image only and now work fine with -Os optimization.

Now how is possible fix this bug of alignement for all the platforms used?

**Comment by kisvegabor** [comment] 2019-02-04 12:48
Great!
And what about image 1?

`LV_ATTRIBUTE_MEM_ALIGN` can be added to `lv_conf.h` where we can add   `__attribute__((aligned(4)))`.

So in the affected repos (where DMA, GPU other harware is used) lvgl and lv_conf.h need to be updated.

**Comment by Simof92** [comment] 2019-02-04 13:11
Image 1 is without alignment of vdb_buff[], if will update every buffer with the alignment the problem could be resolved. 

If you need I can repeat the test of IMG1 with the other buffers aligned

**Comment by Simof92** [comment] 2019-02-04 13:12
> 
> 
> Great!
> And what about image 1?
> 
> `LV_ATTRIBUTE_MEM_ALIGN` can be added to `lv_conf.h` where we can add `__attribute__((aligned(4)))`.
> 
> So in the affected repos (where DMA, GPU other harware is used) lvgl and lv_conf.h need to be updated.

Excellent!

**Comment by kisvegabor** [comment] 2019-02-04 13:20
Awesome! Let's wait @embeddedt's feedback too. If it works for him too than I'll update lvgl master

**Comment by embeddedt** [comment] 2019-02-05 20:58
@Simof92 @kisvegabor I've applied the fixes in all three places (`lv_draw_vbasic.c`, `lv_vdb.c`, and `img_bubble_pattern.c`) and it appears to have solved the problem for me.

Along with those three files, I think we also need to update the bitmap generator in https://github.com/littlevgl/lv_utils to produce `LV_ATTRIBUTE_MEM_ALIGN` on the arrays.

Sorry that it took so long to give feedback; I wanted to send it yesterday but I didn't get a chance to unfortunately.

**Comment by kisvegabor** [comment] 2019-02-06 00:06
> @Simof92 @kisvegabor I've applied the fixes in all three places (`lv_draw_vbasic.c`, `lv_vdb.c`, and `img_bubble_pattern.c`) and it appears to have solved the problem for me.

Awesome! Thanks for the feedback!

> Along with those three files, I think we also need to update the bitmap generator in https://github.com/littlevgl/lv_utils to produce `LV_ATTRIBUTE_MEM_ALIGN` on the arrays.

Yes, they need to be updated. Even an `#ifndef LV_ATTRIBUTE_MEM_ALIGN` guard should be added for backward compatibility.

 > Sorry that it took so long to give feedback; I wanted to send it yesterday but I didn't get a chance to unfortunately.

No worries! :)

**Comment by kisvegabor** [comment] 2019-02-12 04:44
I added `LV_ATTRIBUTE_MEM_ALIGN`.
Please test it.

**Comment by embeddedt** [comment] 2019-02-12 12:16
@kisvegabor Works as expected on my end.

**Comment by kisvegabor** [comment] 2019-02-12 15:28
@embeddedt  Awesome!

**Comment by Simof92** [comment] 2019-02-14 19:53
I would like to update the lvgl submodule in the project but I am not able, I am using github software on windows. 
Could you explain me how to make the pull of submodule?

**Comment by embeddedt** [comment] 2019-02-14 20:38
@Simof92 I think you'll need to use command-line `git` operations to update the submodule.

**Comment by kisvegabor** [comment] 2019-02-15 06:40
Just enter to the `lvgl` folder and `pull`. I'm using the command line and there I run the `git pull origin master` command. So I suppose it should work similarly in a GUI tool

**Comment by embeddedt** [comment] 2019-02-15 12:28
@kisvegabor I think @Simof92 is using GitHub Desktop. I don't think I've ever been able to manipulate submodules with it.

@Simof92 The method @kisvegabor described should work on the command line.

**Comment by Simof92** [comment] 2019-02-15 20:01
> 
> 
> @kisvegabor I think @Simof92 is using GitHub Desktop. I don't think I've ever been able to manipulate submodules with it.
> 
> @Simof92 The method @kisvegabor described should work on the command line.

I'm using GitHub Desktop because the GUI is easy and immediate but now I installed git.

I was able to update the submodules and reconfigure `lv_conf.h` and everything works fine.

@kisvegabor  @embeddedt  Thank you so much for your work

**Comment by kisvegabor** [comment] 2019-02-18 05:27
Awesome! Then I close this issue.

**Closed as completed by kisvegabor** 2019-02-18 05:27 UTC
